# Generated by Django 5.1.5 on 2025-02-15 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='created_timestamp',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_timestamp',
        ),
    ]
