# Generated by Django 5.1.5 on 2025-02-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_address_person_alter_phonenumber_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='JalaliRegistrationDate',
            fields=[
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='jalali_registration_date', serialize=False, to='registry.person')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
